from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return render(request, "services/index.html")
def pembuatanaplikasi(request):    
    SEO1 = ["Desarrollo de Aplicaciones"]
    SEO2 = ["Desarrollo de Aplicaciones"]
    title = ["Desarrollo de Aplicaciones"]
    desc = ["Aplicaciones escolares, aplicaciones de caja de ventas de tiendas y restaurantes, aplicaciones de contabilidad, aplicaciones de tienda en línea, aplicaciones comerciales, aplicaciones de reserva de reservas."]
    img = ["https://1.bp.blogspot.com/-udm1kuJJ_YM/YY_akT1oZHI/AAAAAAAAR3c/k8EXsbU3J4oqNYOMDt_EhT8pH0HqwndSACLcBGAsYHQ/s626/aplikasi%2Bbisnis.jpg"]
    cta = ["Sí, actualmente se necesita una aplicación para las necesidades de los desarrollos tecnológicos modernos en el registro de la contabilidad y el trabajo rápido en tiempo real en línea, esto facilitará que los usuarios con diversas necesidades aceleren, acorten y agreguen movilidad en el trabajo, con esto toda la contabilidad se organizará de forma más ordenada y el seguimiento del rendimiento será aún más fácil.","Aplicación de tienda: es un tipo de aplicación que es muy utilizada en comercios minoristas y mayoristas en su implementación, con esta aplicación podemos trabajar para registrar compras a proveedores, realizar ventas a clientes e imprimir recibos de caja a través de la caja registradora, registrar inventario de gestión de stock , verifique informes detallados como ingresos de facturación, informes de existencias y otras necesidades a través de la propia aplicación de la tienda del cajero y, por supuesto, una variedad de aplicaciones de la tienda están disponibles para ser utilizadas para respaldar su negocio, desde aplicaciones simples a precios bajos hasta aplicaciones completas. para apoyar el desempeño de su negocio.", "Aplicación de restaurante: es un sistema que se necesita para ayudar a acelerar y ordenar la contabilidad en los negocios culinarios, con su capacidad para dividir divisiones y por separado, es muy fácil de usar esta aplicación de restaurante en línea para implementar diversas necesidades en el trabajo, con camareros pedidos de tabletas, pantallas de cocina, hasta que la necesidad del administrador de verificar informes detallados hace posible su uso completo y móvil, por supuesto, hay varias aplicaciones de restaurantes disponibles para respaldar su negocio culinario, desde un sistema simple con precios bajos hasta las funciones completas proporcionado, a partir de reservas de reservas en línea, tiendas de pedidos en línea y otro como él.", "Aplicaciones de contabilidad: aplicación de contabilidad para registrar la contabilidad en función de las necesidades financieras para facilitar la declaración de impuestos para mejorar mediante el registro de transacciones de débito y crédito, con esta función realmente ayuda a que las tareas de contabilidad y contabilidad funcionen rápidamente y admite un sistema simple que es fácil para que los usuarios entiendan." , "La aplicación de facturas es una aplicación que se utiliza para emitir facturas de ventas y facturas de impuestos sobre las ventas y, por supuesto, con soporte completo para la información de contabilidad para empresas, como registrar licitaciones de proyectos con estado de trabajo, hacer ofertas y emitir facturas de ventas y muchos otros.","Las aplicaciones escolares son un requisito completo para que el mundo de la educación acelere diversas necesidades, tanto el proceso de enseñanza como el de aprendizaje, el registro de los libros financieros escolares y varios otros específicos para el mundo de la educación."]
    themes = ["ilxs6l5Dhfw","3eqJz3KqY1M","Xp_sHwn15aQ","tNBRSJKN8N0","RZ6Jl6rxerk","cenxi37fj-8","KUsp5Rzk9Nc","1r7ZbBvBmo0","IK77uOvJ-pU","zQIjZPnGthc","cIChy757jns","u_afMzfjLpE"]
    pricing = ["PRECIOS","La lista de precios y los servicios de la aplicación varían según el paquete y el nivel de dificultad y las funciones utilizadas, por lo que para sus necesidades de aplicaciones web, contáctenos para obtener la mejor solución, no se preocupe, el precio de nuestro servicio es asequible de acuerdo a lo que le ofrecemos."]
    return render(request, "services/pembuatanaplikasi.html",{"SEO1":SEO1,"SEO2":SEO2,"title":title,"img":img,"themes":themes,"desc":desc,"cta":cta,"pricing":pricing})
def pembuatanandroid(request):
    SEO1 = ["Aplicaciones Android"]
    SEO2 = ["Aplicaciones Android"]
    title = ["Aplicaciones Android"]
    desc = ["La solución para hacer su aplicación de información de Android."]
    img = ["https://1.bp.blogspot.com/-YbzqygBEcxY/YY_VwwqTieI/AAAAAAAAR3U/z-d69ct02KwLTevk6ztSmUpSnzdr6sDZQCLcBGAsYHQ/s666/pembuatan%2Bandroid%2Bterbaru.png"]
    cta = ["Ahora, con la tecnología que se está desarrollando con bastante rapidez, tener una aplicación de Android propia puede ayudar a brindar información completa y detallada a los clientes y usuarios de su aplicación de Android, además de eso, también podemos usarla como un medio para promociones de marketing digital para empresas, para tiendas. se puede integrar directamente en los sitios web de la página de compras en línea, o para restaurantes con funciones de pedidos en línea, para spas de salón de barbería con requisitos de reserva en línea, y perfiles de escuelas y empresas para brindar educación e información sobre la empresa, y al tener una aplicación de Android puede úsalo para subirlo a Google Playstore. Tener un APK de Android en PlayStore representará su línea de negocio en el mundo de sus propias aplicaciones, con la integración del sitio web y el APK de Android, tendrá todas las necesidades tecnológicas para respaldar su negocio." , "Usamos varias tecnologías en su implementación, desde el uso nativo de Java Lang, Kotlin, Flutter Dart, hasta el uso de tecnología moderna con un sitio web de aplicación de Android todo en uno en una sola aplicación a través de Angular, React, Svelte, lo que lo hace perfecto para tener un sitio web de Android y en un proceso de construcción, y/o desea utilizar webview para obtener su sitio web en una aplicación de Android, también está disponible a un precio de servicio asequible. así que seleccione el tema a continuación y comience a cargar su aplicación APK de Android en Playstore ahora."]
    themes = ["hvzjFQ7nvoQ" , "UsKbCzS3k4E" ,"v7_Ub0lyvAU" , "1zAHrcDytAc" , "-kht4_wnXho" ,"_9dmDzonKPA" , "3ADJF2yuWC0", "RT7o8Za8Hb4" , "OIO88F0C4Ss", "EtB_3hD9GP4","FnMghNtfap8","itfkpehGPq0"]
    pricing = ["PRECIOS","El paquete estándar cuesta solo $15,000 MXN con instalaciones de 5 páginas más el diseño estándar de Android APK" , "Paquete premium con un costo de solo $30,000 MXN para instalaciones de 5 páginas más un diseño premium Android APK." ,"+ Subir playstore tiene un costo extra de $5,000 MXN" ,"+ La página web cuesta solo $1,000 MXN por página." ,"La vista web para convertir sitios web a aplicaciones de Android cuesta $20,000 MXN (sin incluir las cargas de Playstore)."]
    return render(request, "services/pembuatanandroid.html",{"SEO1":SEO1,"SEO2":SEO2,"title":title,"img":img,"themes":themes,"desc":desc,"cta":cta,"pricing":pricing})
def pembuatanwebsite(request): 
    SEO1 = ["Websites Modernos"]
    SEO2 = ["Websites Modernos"]
    title = ["Websites Modernos"]
    desc = ["La mejor solución para proyectos para crear sitios web de tiendas modernas, restaurantes, cafés, restaurantes, perfiles de empresas y escuelas con la última tecnología moderna."]
    img = ["https://1.bp.blogspot.com/-YN5d4Sv9P8s/YY_awY9_ojI/AAAAAAAAR3o/ZjImPTro0gEEV0JPJvNqsaU8U8JbGCn-QCLcBGAsYHQ/s519/pembuatan%2Bwebsite.png"]
    cta = ["Avance y desarrolle con nuestra tecnología en sus necesidades modernas de creación de sitios web, para tiendas, restaurantes, cafés, restaurantes, escuelas, perfiles de empresas, galerías de arte, artistas y otros campos comerciales, complete sus necesidades de desarrollo web con nosotros para un futuro brillante lo mejor, con una variedad de diseños únicos y atractivos, por supuesto, así como la necesidad de un sistema de administración de contenido completo en la necesidad de un administrador web para administrar el sitio web." , "El soporte tecnológico facilita la elección de acuerdo a tus necesidades y por supuesto incluyendo la aplicación de creación de sitios web, nuestro propio equipo de desarrollo perfeccionará esas necesidades, partiendo de Laravel el php artesanal, symfony, Angular new modern site, o usando Wordpress, Modx Revolutions, al uso de sitios estáticos. Súper rápido, la última generación web con Jekyll, Gatsby, React, Svelte y otros para respaldar la tecnología de su sitio para que sea más perfecto.", "Por supuesto, el paquete premium en sí mismo se ajustará más adelante a las necesidades de trabajo, comenzando con la colaboración tecnológica para producir un sitio que esté realmente actualizado y soporte para varios marcos para completar el desarrollo de su proyecto de proyecto más completo, y ahora es el momento de comenzar a utilizar nuestros servicios de creación de sitios web para obtener los mejores resultados. , elija un tema a continuación, elija su dominio y su sitio web está en línea, es hora de que la revolución digital comience con nosotros."]
    themes = ["sMENkpTFTFU" , "H3B0cCc7TcU" , "06lHpX0Fmfk" , "wuvIR7W34M4" , "kIV2DEjHwKg", "fqmIvmc1O_A" , "FOKuedSKZc4" , "BWpSHiOjIZo" , "KgaCUaVdyYE" , "AI2fLF6bgvE", "mDs8BirlC5o" , "9hIJzVtdfxo","PcmgkuQEJRA" , "lxOpSoThms8" , "vqbeeSLq-Fo"]
    pricing = ["PRECIOS", "BÁSICO: $10,000 MXN con temas estándar + dominio .net + espacio web 250 MB | ESTÁNDAR: $15,000 MXN con temas estándar + dominio .com + espacio web 500 MB | PREMIUM: $25,000 MXN con temas premium + aplicaciones POS + dominio .com + espacio web 1.500 MB" , "Sistema de gestión de contenido: Laravel, Symfony, Modx, Wordpress: $20,000 MXN con dominio .com + espacio web 500 MB","Whatsapp online shop - BÁSICO: $10,000 MXN con dominio .net + 250MB Espacio web | ESTÁNDAR: $15,000 MXN con dominio .com + 500 MB de espacio web + código QR digital", "Aplicación web de lujo Python Django, Golang, Ruby on Rails solo por $25,000 MXN que incluye 5 diseños de página", "Sitio moderno: Gatsby, React, Angular, Svelte, Jekyll + 5 páginas por $25,000 MXN, la renovación de dominio .com por año tiene costo extra de $5,000 MXN por año" , "Personalizado: Para colaboración tecnológica con integración de sitio web + tienda en línea + aplicación de cajero de tienda a solo $35,000 MXN"]
    return render(request, "services/pembuatanwebsite.html",{"SEO1":SEO1,"SEO2":SEO2,"title":title,"img":img,"themes":themes,"desc":desc,"cta":cta,"pricing":pricing})
